feat: add eslint rule
daichan2019/miminari-app pull request #10
Opened 2023-03-11 10:25 UTC by daichan2019

close #2

2023-03-11 11:55 UTC, piro0919 requested changes

2023-03-11 11:55 UTC, piro0919 commented on .eslintrc.json
> +    // React
[nits]

json ファイルにコメントは書くべきではないですね。 🙅‍♂️

2023-03-11 11:55 UTC, piro0919 commented on package.json
> +    "fix:lint": "next lint --fix"
[imo]

命名がイマイチですね。

`lint:fix`

2023-03-11 11:55 UTC, piro0919 commented on package.json
> +  "devDependencies": {
[must]

最新の Next.js では devDependencies を使う理由がなくなりました−。
dependencies にまとめるようにしましょう。

2023-03-11 11:55 UTC, piro0919 commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0"
[must]

バージョンは固定してインストールすべきですね！

2023-03-11 13:02 UTC, daichan2019 commented on package.json
> +    "fix:lint": "next lint --fix"
@piro0919 
prettierとstylelintを追加した際、修正scriptの命名を`fix:prettier`, `fix:style`で追加したい意図があるので、`fix:eslint`に変更しました。

[54b0b46](https://github.com/daichan2019/miminari-app/pull/10/commits/54b0b46dafaa03e9154fb92333bf58687b7cd620)

2023-03-11 13:03 UTC, daichan2019 commented on package.json
> +  "devDependencies": {
@piro0919 
こちらのcommitでnpmrcを追加し、dependenciesに再インストールし直しました。
[51db3cf](https://github.com/daichan2019/miminari-app/pull/10/commits/51db3cf4b99fe4ab044abfaa9d6f445c34b739c3)

2023-03-11 13:04 UTC, daichan2019 commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0"
@piro0919 
上記と同じくnpmrcに`save-exact=true`を追記し、再インストールし直しました。

[51db3cf](https://github.com/daichan2019/miminari-app/pull/10/commits/51db3cf4b99fe4ab044abfaa9d6f445c34b739c3)

2023-03-11 13:05 UTC, daichan2019 commented on .eslintrc.json
> +    // React
@piro0919 
コメントアウト削除しました。
[54b0b46](https://github.com/daichan2019/miminari-app/pull/10/commits/54b0b46dafaa03e9154fb92333bf58687b7cd620)

2023-03-11 13:12 UTC, piro0919 commented on package.json
> +  "devDependencies": {
@daichan2019 

.npmrc の追加は Issue を立てて対応したほうが良いと思いますね。 👀

2023-03-11 13:25 UTC, daichan2019 commented on package.json
> +  "devDependencies": {
@piro0919 
.npmrcは削除しました。
別でissueたてて追加のPR出します。

[d84caa3](https://github.com/daichan2019/miminari-app/pull/10/commits/d84caa3835592f6c3852fdeaff965b4737e84a42)

2023-03-12 13:18 UTC, piro0919 approved these changes
LGTM 👍

2023-03-12 23:15 UTC, merged