feat: add stylelint packages and lint scripts
daichan2019/miminari-app pull request #14
Opened 2023-03-14 12:41 UTC by daichan2019

close #5

2023-03-14 15:16 UTC, piro0919 requested changes

2023-03-14 23:22 UTC, daichan2019 commented on package.json
> +    "lint:style": "stylelint 'src/**/*.{css,less,sass,scss}'",
@piro0919 
scssは使うかもしれないことを考慮してless, sassは取り除きました。
[2a6c456](https://github.com/daichan2019/miminari-app/pull/14/commits/2a6c456ec41570625345a2976db245ee94c85b91)

2023-03-15 02:20 UTC, piro0919 requested changes

2023-03-15 02:20 UTC, piro0919 commented on package.json
> +    "lint:style": "stylelint 'src/**/*.{css,scss}'",
[must]

今回って CSS と Sass の両方導入するんでしたっけ？ 👀

2023-03-15 13:22 UTC, daichan2019 commented on package.json
> +    "lint:style": "stylelint 'src/**/*.{css,scss}'",
@piro0919 
もしかしたら今後scssも使うことも考慮してましたが、現状いらないので削除しました。

[37af924](https://github.com/daichan2019/miminari-app/pull/14/commits/37af92448ab7d1a804f43f48d72d6a564a041c4c)

2023-03-15 13:24 UTC, piro0919 approved these changes
LGTM 👍

2023-03-15 13:24 UTC, merged