feat: add prettier
daichan2019/miminari-app pull request #16
Opened 2023-03-14 13:15 UTC by daichan2019

close #8

2023-03-14 15:15 UTC, piro0919 requested changes

2023-03-14 15:15 UTC, piro0919 commented on package.json
> +    "*.{js,jsx,ts,tsx}": "eslint --fix",
[must]

Next の lint を使うべきかなと。

https://nextjs.org/docs/basic-features/eslint#lint-staged

2023-03-14 23:26 UTC, daichan2019 commented on package.json
> +    "*.{js,jsx,ts,tsx}": "eslint --fix",
@piro0919 
next lintで動かすように修正しました
[56e611a](https://github.com/daichan2019/miminari-app/pull/16/commits/56e611a905b24f9137d95284861110ee4ef0562e)

2023-03-15 13:26 UTC, piro0919 requested changes

2023-03-15 13:26 UTC, piro0919 commented on package.json
> +    "*.{js,jsx,ts,tsx}": "next lint --fix",
[must]

Next の公式と書きっぷりが違いますが、これで動きました…？
あえて公式の書き方と変えたのであれば、理由がほしいですね。 👀 

rel https://github.com/daichan2019/miminari-app/pull/16#discussion_r1135719085

2023-03-15 14:14 UTC, daichan2019 commented on package.json
> +    "*.{js,jsx,ts,tsx}": "next lint --fix",
@piro0919 
`eslint fix`→`next lint`へ変更したら動かなかったです...
`next lint`へ変更した際に動作検証してませんでしたmm
公式通り記述し、動作検証OKでした

[085b23a](https://github.com/daichan2019/miminari-app/pull/16/commits/085b23aaafc98f5db06ef232dc868f5f0ddbadee)

2023-03-16 12:34 UTC, merged