feat: add header
daichan2019/miminari-app pull request #22
Opened 2023-03-28 13:48 UTC by daichan2019

close #21

2023-03-28 14:54 UTC, piro0919 requested changes

2023-03-28 14:54 UTC, piro0919 commented on src/components/header/index.tsx
> +export default function Header(): JSX.Element {
[must]

フォルダ名は upper にしましょうー。

2023-03-28 14:54 UTC, piro0919 commented on src/app/page.tsx
>  export default async function Home() {
[imo]

スコープ外ですが、ついでにコンポーネント名も `Page` とかにしたほうが良いかなと。

2023-03-28 14:54 UTC, piro0919 commented on src/app/page.module.css
>  .main {
[must]

このファイルを残した意味はなんでしょうー。

2023-03-29 13:30 UTC, daichan2019 commented on src/app/page.module.css
>  .main {
現時点で不要なので削除しました。

[18d4ab5](https://github.com/daichan2019/miminari-app/pull/22/commits/18d4ab5e537a326e501cef2e33eacf28d89b8b04)

2023-03-29 13:35 UTC, daichan2019 commented on src/components/header/index.tsx
> +export default function Header(): JSX.Element {
僕もUpperにしていたのですが、MacOSがデフォルトで大文字と小文字を区別しないファイルシステムのようで、手元の環境で`MyComponent.js`を`myComponent.js`とrenameしてもGitがファイル名変更を拾ってくれず、GitHub ActionsなどのCIで初めて怒られてしまう、ということを見てから、プライベート開発ではcomponent名をkebab-caseで命名するようにしています。

ref
https://profy.dev/article/react-folder-structure#kebab-case-for-file-and-folder-names
https://twitter.com/kentcdodds/status/1249870276688371713

2023-03-29 14:19 UTC, piro0919 commented on src/components/header/index.tsx
> +export default function Header(): JSX.Element {
@daichan2019 

気持ちはわかりますが、一般的な考え方ではないと思います。
エビデンスとしてもかなり弱いですし、個人的には賛同できないですね。 🙅‍♂️ 

Git がファイル名の変更を拾わないのは正しい仕様ですから、きちんと Issue を立てて対応すべきかと個人的には。

2023-03-29 14:21 UTC, piro0919 requested changes

2023-03-29 14:21 UTC, piro0919 commented on src/app/globals.css
>    color: rgb(var(--foreground-rgb));
[must]

この変数って残ってますっけ？ 👀

2023-03-30 14:32 UTC, piro0919 approved these changes
LGTM 👍

2023-03-31 13:23 UTC, merged