feat: add sounds list
daichan2019/miminari-app pull request #26
Opened 2023-04-11 12:49 UTC by daichan2019

close #23

2023-04-11 12:54 UTC, piro0919 requested changes

2023-04-11 12:54 UTC, piro0919 commented on src/app/page.tsx
> +      return {
[imo]

ワンライナーでー。

2023-04-11 12:54 UTC, piro0919 commented on src/components/SoundList/index.tsx
> +            <p>{title}</p>
[imo]

div のほうが良いですね。

2023-04-11 12:54 UTC, piro0919 commented on src/components/SoundList/index.tsx
> +              <div style={{ height: '60px', width: '60px' }}>
[nits]

？ 👀

2023-04-20 12:21 UTC, daichan2019 commented on src/app/page.tsx
> +      return {
ここのreturnはeslintによって縛っています。
個人的には、returnありなしをeslintで縛りたいので、以下のeslintでreturnを必ず書くようにしています。
なおしたほうが良さげでしたらeslintの設定を変更してここも直します...

```
"arrow-body-style": ["error", "always"],
```

2023-04-20 12:25 UTC, daichan2019 commented on src/app/page.tsx
> +  const soundsData: SoundsData = await fetchSounds();
削除しました＠

[f66b898](https://github.com/daichan2019/miminari-app/pull/26/commits/f66b898ef2bbf217c3a7bc605b6b3c0d6fa28256)

2023-04-20 12:26 UTC, daichan2019 commented on src/components/SoundList/index.tsx
> +            <p>{title}</p>
divへ変更しました！

[ff957d0](https://github.com/daichan2019/miminari-app/pull/26/commits/ff957d0694b6b9f3cac3a063d71cedc665985fa2)

2023-04-20 12:26 UTC, daichan2019 commented on src/components/SoundList/index.tsx
> +              <div style={{ height: '60px', width: '60px' }}>
不要なので削除しました

[111116b](https://github.com/daichan2019/miminari-app/pull/26/commits/111116b9698d4b0034770d0c6d2ba53338d9da97)

2023-04-20 15:17 UTC, piro0919 approved these changes
LGTM 👍

2023-04-22 07:22 UTC, merged